x = int(input('Digite o valor em metros: '))
print('O valor em centimentros é {}, e em milímetros é {}'.format(x*100,x*1000))
print('A tabuada de {} é:'.format(x))
print('-' * 12)
print('1 x {} = {}'.format(x,x))
print('2 x {} = {}'.format(x,x*2))
print('3 x {} = {}'.format(x,x*3))
print('4 x {} = {}'.format(x,x*4))
print('5 x {} = {}'.format(x,x*5))
print('6 x {} = {}'.format(x,x*6))
print('7 x {} = {}'.format(x,x*7))
print('8 x {} = {}'.format(x,x*8))
print('9 x {} = {}'.format(x,x*9))
print('10 x {} = {}'.format(x,x*10))
print('-' * 12)